# Generated by Django 3.1.3 on 2020-11-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20201103_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='payment_methdos',
            new_name='payment_methods',
        ),
    ]
