# Generated by Django 3.1.3 on 2020-11-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20201103_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='customomer',
            new_name='customer',
        ),
    ]
